baseurl = "https://aosmith.rbind.io/"
languageCode = "en-us"
title = "Very statisticious"
theme = "hugo-future-imperfect"
enableEmoji = true
# preserveTaxonomyNames = true
disqusShortname = ""
googleAnalytics = ""
pluralizeListTitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  # Sets the meta tag description
  description          = ""
  author               = "Ariel Muldoon"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Very statisticious"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/post/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = false
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = false
  rssAppearAtBottom    = false
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = false
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]

# Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
# due to its ease of use. Feel free to check out both and decide what you would
# prefer to use. See Staticman.yml for additional settings.
[params.staticman]
  # Sets Statiman to be active
  staticman = false
  # Sets the location for Staticman to connect to
  username  = ""
  repo      = ""
  branch    = ""

  [params.staticman.recaptcha]
    sitekey = "SITE_KEY"
    secret  = "ENCRYPTED_SECRET"

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "Very Statisticious"

  paragraph = "I discuss issues I've found come up regularly during statistical analysis and how to solve them using R"

  about     = "I currently work as a consulting statistician, advising natural and social science researchers on statistics, statistical programming, study design, etc.  I also create and teach R workshops for applied science graduate students who are just getting started in R.  My goal is to make their transition to a programming language as smooth as possible."

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/ao_ppg2.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = true
    width     = ""
    alt       = ""

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = ""
  identifier = "fa fa-home"
  weight = 1

# [[menu.main]]
#  name = "About"
#  url = "/about/"
#  identifier = "fa fa-id-card-o"
#  weight = 2

[[menu.main]]
  name = "Posts"
  url = "/post/"
  identifier = "fa fa-newspaper-o"
  weight = 2

# [[menu.main]]
#  name = "Categories"
#  url = "/categories/"
#  identifier = "fa fa-sitemap"
#  weight = 4

# I'm removing the Contact page because I'm having
     # trouble getting it to show up right
# [[menu.main]]
#  name = "Contact"
#  url = "/contact/"
#  identifier = "fa fa-envelope-o"
#  weight = 3

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github          = "aosmith16"
  gitlab          = ""
  stackoverflow   = "2461552" # User Number
  bitbucket       = ""
  jsfiddle        = ""
  codepen         = ""
  # Visual Art Communities
  deviantart      = ""
  flickr          = ""
  behance         = ""
  dribbble        = ""
  # Publishing Communities
  wordpress       = ""
  medium          = ""
  # Professional/Business Oriented Communities
  linkedin        = ""
  foursquare      = ""
  xing            = ""
  slideshare      = ""
  # Social Networks
  facebook        = ""
  googleplus      = ""
  reddit          = ""
  quora           = ""
  youtube         = ""
  vimeo           = ""
  whatsapp        = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat          = ""
    qq              = "" # User ID Number
  instagram       = ""
  tumblr          = ""
  twitter         = "aosmith16"
  skype           = ""
  snapchat        = ""
  pinterest       = ""
  telegram        = ""
  vine            = ""
  # Email
  email           = "ariel.muldoon@gmail.com"
